# Generated by Django 3.2.4 on 2024-08-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20240823_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='', max_length=10),
        ),
    ]
